service: lambda-ts-manual

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  environment:
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}
    COGNITO_CLIENT_SECRET: ${env:COGNITO_CLIENT_SECRET}
    COGNITO_REDIRECT_URI: ${env:COGNITO_REDIRECT_URI}
    COGNITO_DOMAIN: ${env:COGNITO_DOMAIN}

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

functions:
  hello:
    handler: dist/handlers/hello.hello
    events:
      - httpApi:
          path: /
          method: GET

  authCallback:
    handler: dist/handlers/callback.handler
    events:
      - httpApi:
          path: /api/auth/callback/google
          method: POST

  authVerify:
    handler: dist/handlers/auth-verify.handler
    events:
      - httpApi:
          path: /api/auth/verify
          method: GET

custom:
  serverless-offline:
    httpPort: 8888
